In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('sample.csv')

In [3]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [4]:
from sentence_transformers import SentenceTransformer

In [5]:
encorder = SentenceTransformer('bert-base-nli-mean-tokens')
vector=encorder.encode(df.text)
vector.shape

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

c:\Python312\Lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\saifu\.cache\huggingface\hub\models--sentence-transformers--bert-base-nli-mean-tokens. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.99k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(8, 768)

In [6]:
vector

array([[ 0.04833933,  0.29556116,  0.79127073, ...,  0.07494575,
        -0.93341804, -0.8458563 ],
       [-0.52396894, -0.10749719, -0.11692888, ...,  0.03128514,
        -0.66294795, -0.29896387],
       [-0.30924866, -0.44102192,  2.1799479 , ..., -1.318974  ,
         0.09969992, -0.32386187],
       ...,
       [-0.13673231, -0.32200357,  1.3394136 , ..., -0.26709273,
         0.3961509 , -0.00685968],
       [ 0.1388734 , -0.71958727,  2.7110808 , ..., -0.609554  ,
        -0.6455009 , -0.659427  ],
       [-0.24585438, -0.15886363,  0.53315   , ...,  0.33926275,
         0.2948122 , -0.45117202]], dtype=float32)

In [7]:
import faiss

In [8]:
dim = vector.shape[1]
dim

768

In [9]:
index = faiss.IndexFlatL2(dim) #it create l2 distance index to faster search
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001C617169830> >

In [10]:
#above is a empty index. then add vectors 
index.add(vector)

In [17]:
search_query = 'I want to buy a polo t-shirt'

vec=encorder.encode(search_query)
vec.shape

(768,)

In [18]:
#above is a 1 dimensional array. but faiss need 2 dimensional array
#so covert this vec to  2 dimensional array
import numpy as np

svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [19]:
svec

array([[ 0.88021094, -1.101029  ,  0.55957836,  0.30793497,  0.8335651 ,
        -0.54538035, -0.45192918,  0.16884471,  1.1219397 , -0.74239117,
        -0.58252454,  1.0003726 , -0.576151  ,  0.88928103,  0.375093  ,
         0.53106695, -0.06653848,  0.6261907 , -0.01071582,  0.32650086,
        -0.50601333,  0.2828875 ,  0.22365794,  1.0091164 ,  1.22609   ,
        -0.5043221 ,  0.2624034 ,  0.3365692 , -0.09629243,  0.5131474 ,
         0.5644836 , -0.43442866,  0.21200873, -0.23816301, -0.19327264,
         0.406573  , -0.5441899 , -0.3591799 ,  0.12578012, -1.1164244 ,
        -0.00835758, -0.2329154 , -0.16827969,  0.05013546, -1.0635887 ,
        -0.9341193 , -0.19780225,  0.47088137, -0.7640505 , -1.6057136 ,
         0.2685868 , -0.51491314, -0.20480342,  0.0996337 , -0.48771417,
         1.2057369 , -0.5122699 , -0.7747336 , -0.59529483, -0.97559285,
        -0.6177825 ,  0.14407198,  0.59366316,  0.72085756, -0.07431664,
        -0.0253175 , -0.41270322, -0.6498542 , -0.7

In [20]:
index.search(svec,k=2) #k=2 means return 2 nearest vectors

(array([[268.44415, 325.8689 ]], dtype=float32), array([[3, 2]], dtype=int64))

In [21]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [22]:
distances,indexes=index.search(svec,k=2)

In [23]:
distances

array([[268.44415, 325.8689 ]], dtype=float32)

In [24]:
indexes

array([[3, 2]], dtype=int64)

In [25]:
df.loc[[0,5]]

text category
0      Meditation and yoga can improve mental health   Health
5  Navaratri dandiya program at Expo center in Mu...    Event

In [26]:
df.loc[[3,2]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [27]:
search_query2="Eating apple make the day better"
vec2=encorder.encode(search_query2)
vec2

array([-4.60781515e-01,  2.52003461e-01,  1.42859876e-01, -5.36996484e-01,
       -9.03198868e-02, -1.54597357e-01, -2.59388864e-01,  7.76224136e-01,
        5.41064262e-01, -1.11982465e+00, -7.81175680e-03,  8.09857845e-01,
        2.62865692e-01, -2.66493052e-01, -8.74067843e-02, -2.09901035e-02,
        2.41274670e-01, -2.88406014e-01,  1.80241652e-03,  3.00842039e-02,
       -1.37662411e-01, -6.02822602e-01, -5.79477429e-01, -2.53988445e-01,
        6.14683211e-01, -6.37873054e-01, -3.45617473e-01,  5.72284341e-01,
        6.89331412e-01, -5.04543304e-01, -4.06040549e-01,  1.18598557e+00,
        3.20455879e-01, -3.60711932e-01, -1.79457918e-01,  1.32051253e+00,
        1.27918139e-01, -8.32339048e-01, -7.61729628e-02,  5.02964199e-01,
        6.06207371e-01, -7.14872241e-01,  1.15601175e-01,  1.11764222e-02,
       -1.00184500e+00, -3.38751316e-01, -7.50593781e-01,  2.93435365e-01,
        1.69595480e-01,  3.06878276e-02,  1.08263338e+00, -2.16578305e-01,
       -6.73876777e-02, -

In [28]:
vec2.shape

(768,)

In [29]:
svec2=np.array(vec2).reshape(1,-1)
svec2.shape

(1, 768)

In [30]:
index.search(svec2,k=2)

(array([[198.22383, 270.45926]], dtype=float32), array([[1, 0]], dtype=int64))

In [31]:
df.loc[[1,0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health